apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: maxkoz777/moscow_time_python
        ports:
        - containerPort: 8080