apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-application-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app-container
        image: maxkoz777/moscow_time_java
        ports:
        - containerPort: 8080