MY_PASS: ENC[AES256_GCM,data:rTjeiuI=,iv:wbqLrkYssDMkMzaNBiMm/+9asYfBhahT3pJTgI08xIU=,tag:o4XU0FaGSmU5kmFqNE/e/Q==,type:str]
sops:
   lastmodified: "2022-11-15T02:13:47Z"
   mac: ENC[AES256_GCM,data:FTCo/bMG/iaCAIyAAOeU3crHLb2+njmtc006BDyhVUfVEoOqosR0ax8GZ5ToBwxK6xhZwgC7LFj7nu19QQmRizZK9rgA2bBxMG29UwUgVWaCOG5O8QFm2Ef3z3JoWi/9ZVoPd9Q/FNeJpLKf4h1pJ3yN4OCQ5tHwWEf6s7ykSkg=,iv:bnTWzJ2k3BscGBja2w87HvrsXh1kpKtUUxIpsb8dGVv=,tag:XjZViq2fdwfpg4Q0yRg85T==,type:str]
   pgp:
       - created_at: "2022-11-15T02:13:47Z"
         enc: |
           -----BEGIN PGP MESSAGE-----

           tpptcyNijK6fKGvfhyi8xOyF46Hw1aNCFc0oJpVpwYAaqpPFE7Kqej9+18E5Buxr
           OTHgnbz4cW/ISeEabsa+0lwBrEd+MIEwC7f2YgSi4X5arzoRP/Y/GojaOttHfHMk
           9WmqvMAMeFBmFX9Un+/Pff55o0Hg9Ru4fRh2RxKIMRwQDUzQjDSVkIdLn3IDULb0
           pf9B9Wvvw9Xc0qzZH47h7qHLJxEaDFjtoio757bybckyBibde+6y0UuzmH7zT6nu
           W6hwbNCJbJcKCXpTBOvs0O9H866Ixb9D0CO2oFDanVnyOae/n+7Yb/LWAZeRdufs
           75OKfoJXjA8sOadDfQ/4VMLqrByGRN+f1JKY8rfGH+azBF7l2pb0wDGgWUzVn4Dq
           6Cu2wzALZFEExJ1vMyMBKZUvIVzdPZzOMzcgFxBb2OA9tAn0tw48lKrZNGyPaWF+
           EBljCDGCeVai+N2EM72OSH11FYXuXcFqNLYVFepEZAXUZmpxA7XgXcxyNTzWEI62
           S5n9VEi0GgqDGCA5LA==
           =yhEg
           -----END PGP MESSAGE-----
         fp: 98459A92CB36A79D211C88FB35E5238BFB7C475B
   unencrypted_suffix: _unencrypted
   version: 3.7.3